name: Release

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    continue-on-error: true
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: linux-x64
          - os: ubuntu-24.04-arm
            arch: linux-arm64
          - os: windows-latest
            arch: windows-x64
          - os: macos-latest
            arch: macos-arm64
          - os: macos-13
            arch: macos-x64
    env:
      ZIP_NAME: cloud-cleaner-aws_${{ matrix.arch }}_${{ github.event.release.tag_name }}.zip
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'graalvm'
        java-version: '21'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - run: ls -l /home/runner/.gradle/jdks/graalvm_community-21-amd64-linux.2/bin/
    - name: Build with Gradle Wrapper
      run: ./gradlew nativeCompile
    - name: Zip nativeCompile
      run: |
        mkdir -p dist
        cp -r cloud-cleaner-aws/build/native/nativeCompile ./dist/
        cd dist
        zip -r "$ZIP_NAME" *
    - name: Upload result to release
      run: gh release upload ${{ github.event.release.tag_name }} "./dist/$ZIP_NAME" --clobber